// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetActiveAdapter() {
  return window['go']['main']['App']['GetActiveAdapter']();
}

export function GetAllowedActions(arg1) {
  return window['go']['main']['App']['GetAllowedActions'](arg1);
}

export function GetProjectDirectory() {
  return window['go']['main']['App']['GetProjectDirectory']();
}

export function IsActionAllowed(arg1) {
  return window['go']['main']['App']['IsActionAllowed'](arg1);
}

export function ListAdapters() {
  return window['go']['main']['App']['ListAdapters']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RevealProjectDirectory(arg1) {
  return window['go']['main']['App']['RevealProjectDirectory'](arg1);
}

export function SaveSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3, arg4);
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SendAnswer(arg1, arg2) {
  return window['go']['main']['App']['SendAnswer'](arg1, arg2);
}

export function SendApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendApproval'](arg1, arg2, arg3);
}

export function SendDiffDecision(arg1, arg2) {
  return window['go']['main']['App']['SendDiffDecision'](arg1, arg2);
}

export function SendPlanDecision(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPlanDecision'](arg1, arg2, arg3);
}

export function SetActiveAdapter(arg1) {
  return window['go']['main']['App']['SetActiveAdapter'](arg1);
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowQuit() {
  return window['go']['main']['App']['WindowQuit']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
