// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveAdapter():Promise<string>;

export function GetProjectDirectory():Promise<string>;

export function ListAdapters():Promise<Array<Record<string, string>>>;

export function SelectProjectDirectory():Promise<string>;

export function SendAnswer(arg1:string,arg2:string):Promise<void>;

export function SendApproval(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetActiveAdapter(arg1:string):Promise<void>;

export function SetProjectDirectory(arg1:string):Promise<void>;

export function StartTask(arg1:string,arg2:string):Promise<void>;

export function StopTask():Promise<void>;
