// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteSession(arg1:string):Promise<void>;

export function GetActiveAdapter():Promise<string>;

export function GetAllowedActions(arg1:string):Promise<Array<string>>;

export function GetProjectDirectory():Promise<string>;

export function IsActionAllowed(arg1:string):Promise<boolean>;

export function ListAdapters():Promise<Array<Record<string, string>>>;

export function ListSessions():Promise<Array<domain.SessionSummary>>;

export function LoadSession(arg1:string):Promise<domain.Session>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RevealProjectDirectory(arg1:string):Promise<void>;

export function SaveSession(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function SelectProjectDirectory():Promise<string>;

export function SendAnswer(arg1:string,arg2:string):Promise<void>;

export function SendApproval(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SendDiffDecision(arg1:string,arg2:Record<string, boolean>):Promise<void>;

export function SendPlanDecision(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function SetActiveAdapter(arg1:string):Promise<void>;

export function SetProjectDirectory(arg1:string):Promise<void>;

export function StartTask(arg1:string,arg2:string):Promise<void>;

export function StopTask():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowQuit():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
