// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveAdapter() {
  return window['go']['main']['App']['GetActiveAdapter']();
}

export function GetProjectDirectory() {
  return window['go']['main']['App']['GetProjectDirectory']();
}

export function ListAdapters() {
  return window['go']['main']['App']['ListAdapters']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SendAnswer(arg1, arg2) {
  return window['go']['main']['App']['SendAnswer'](arg1, arg2);
}

export function SendApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendApproval'](arg1, arg2, arg3);
}

export function SetActiveAdapter(arg1) {
  return window['go']['main']['App']['SetActiveAdapter'](arg1);
}

export function SetProjectDirectory(arg1) {
  return window['go']['main']['App']['SetProjectDirectory'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}

export function StopTask() {
  return window['go']['main']['App']['StopTask']();
}
